name: My First file
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 
            - uses: actions/checkout@v7

            - name: Welcome
              run: echo "Welcome All"
            
            - name: Display contents
              run: cat one.txt
              

    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: ls