name: My First file
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Welcome
              run: echo "Welcome All"
              

    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: ls