name: Practice Actions
on: push
jobs:
    generate_file:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: generate ASCII
              run: |
                   chmod +x generate.sh
                   ./generate.sh

            - name: upload artifact
              uses: actions/upload-artifact@v7
                with:
                    name: my-artifact
                    path: dragon.txt
    
    display_file:
        needs: generate_file
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v7
                with:
                    name: my-artifact
                    
            - name: display file
              run: cat dragon.txt